export default {
  role: "admin",
  id: 1,
  fname: "Test",
  teachers: [
    { name: "Teacher 1", id: 2, location: "USA" },
    { name: "Teacher 2", id: 3, location: "Canada" },
  ],
  tasks: [
    {
      id: "1",
      task_name: "Sample task 1",
      task_description: "Sample description 1",
      completion: "false",
      assignee: "Sample person 1",
      assignedBy:"Sample Admin 11",
    },
    {
      id: "2",
      task_name: "Sample task 2",
      task_description: "Sample description 2",
      completion: "true",
      assignee: "Sample person 2",
      assignedBy:"Sample Admin 15",
    },
    {
      id: "3",
      task_name: "Sample task 3",
      task_description: "Sample description 3",
      completion: "false",
      assignee: "Sample person 3",
      assignedBy:"Sample Admin 101",
    },
    {
      id: "4",
      task_name: "Sample task 4",
      task_description: "Sample description 4",
      completion: "true",
      assignee: "Sample person 4",
      assignedBy:"Sample Admin 118",
    },
    {
      id: "8",
      task_name: "Sample task 10",
      task_description: "Sample description 10",
      completion: "false",
      assignee: "Sample person 5",
      assignedBy:"Sample Admin 98",
    },
    {
      id: "12",
      task_name: "Sample task 12",
      task_description: "Sample description 12",
      completion: "true",
      assignee: "Sample person 6",
      assignedBy:"Sample Admin 21",
    },
    {
      id: "31",
      task_name: "Sample task 31",
      task_description: "Sample description 31",
      completion: "false",
      assignee: "Sample person 8",
      assignedBy:"Sample Admin 1",
    },
    {
      id: "42",
      task_name: "Sample task 42",
      task_description: "Sample description 42",
      completion: "true",
      assignee: "Sample person 7",
      assignedBy:"Sample Admin 17",
    },
  ],
};
